import "./style.scss";
import "./lib_js/header_structure.js"
import "./lib_js/footer_structure.js"
import "./lib_js/mainpage_structure.js";
import "./lib_js/mentionspage_structure.js";
import "./lib_js/mentionspage_content.js";
import "./lib_js/list_title.js";
import "./lib_js/list_columns.js";
import "./lib_js/menu_action.js";
import "./lib_js/menu_create.js";
import "./lib_js/add_task_modal.js";
import "./lib_js/togglemode.js";
import "./lib_js/searchbar.js";
import "./lib_js/transition.js";
